# Generated by Django 4.1 on 2022-08-17 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('wallet', models.PositiveBigIntegerField()),
                ('type_sponsor', models.CharField(choices=[('yuridik', 'yuridik'), ('jismoniy', 'jismoniy')], max_length=15)),
                ('status', models.CharField(choices=[('yangi', 'yangi'), ('moderatsiyada', 'moderatsiyada'), ('tasdiqlangan', 'tasdiqlangan')], default='yangi', max_length=25)),
                ('organization_name', models.CharField(blank=True, max_length=250, null=True)),
                ('datesp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('otm', models.CharField(max_length=250)),
                ('type_student', models.CharField(max_length=100)),
                ('contract_summ', models.PositiveBigIntegerField()),
                ('wallet', models.PositiveBigIntegerField(default=0)),
                ('datest', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_st', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.PositiveBigIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base_app.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base_app.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
