# Generated by Django 4.1 on 2022-08-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
            preserve_default=False,
        ),
    ]
