# Generated by Django 4.1 on 2022-08-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_worker_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='base.category'),
        ),
    ]
